import type { TierColor, ResetCycle, StatusProgram } from './loyalty';

// ─────────────────────────────────────────────────────────────
// Steps
// ─────────────────────────────────────────────────────────────
export type ProgramStepId = 'setup' | 'tiers' | 'benefits' | 'rules' | 'review';
export const PROGRAM_STEPS: { id: ProgramStepId; short: string; label: string }[] = [
  { id: 'setup', short: 'Setup', label: 'Program setup' },
  { id: 'tiers', short: 'Tiers', label: 'Tier structure' },
  { id: 'benefits', short: 'Benefits', label: 'Benefits & cashback' },
  { id: 'rules', short: 'Rules', label: 'Progression rules' },
  { id: 'review', short: 'Review', label: 'Review & publish' },
];

// ─────────────────────────────────────────────────────────────
// Cashback / rakeback
// ─────────────────────────────────────────────────────────────
export type CashbackModel = 'net_loss' | 'turnover' | 'ggr';
export const CASHBACK_MODEL_META: Record<CashbackModel, { label: string; short: string; desc: string; metric: string }> = {
  net_loss: { label: 'Net-loss cashback', short: 'Net loss', desc: 'Pay back a % of a player’s net losses over the period.', metric: 'net loss' },
  turnover: { label: 'Turnover rakeback', short: 'Turnover', desc: 'Rakeback on total amount wagered, win or lose.', metric: 'turnover' },
  ggr: { label: 'GGR rakeback', short: 'GGR', desc: 'Share of gross gaming revenue generated by the player.', metric: 'GGR' },
};
export type PayoutFrequency = 'daily' | 'weekly' | 'monthly';

export interface CashbackConfigState {
  model: CashbackModel;
  payoutFrequency: PayoutFrequency;
  maxPayoutCap: number;    // per player per period
  minEligibility: number;  // min metric value to qualify
  excludedSegments: string[];
}

// ─────────────────────────────────────────────────────────────
// Tiers
// ─────────────────────────────────────────────────────────────
export interface TierCriteria { wager: number; netLoss: number; deposits: number; activeDays: number; }
export interface TierBenefits {
  cashbackPct: number;
  rewardMultiplier: number;
  xpMultiplier: number;
  withdrawalPerk: string;
  vipManager: boolean;
  perks: string[];
}
export interface DraftTier {
  id: string;
  name: string;
  color: TierColor;
  entry: TierCriteria;
  maintain: TierCriteria;
  benefits: TierBenefits;
  estPlayers: number; // projected population — feeds liability preview
}

export const BONUS_PERKS = ['Birthday bonus', 'Weekly free spins', 'Priority support', 'Exclusive tournaments', 'Reload bonuses', 'Cashback insurance'];
export const WITHDRAWAL_PERKS = ['Standard', 'Priority (24h)', 'Instant', 'Dedicated VIP payout'];
export const CRITERIA_COLS: { key: keyof TierCriteria; label: string; prefix?: string; suffix?: string }[] = [
  { key: 'wager', label: 'Wager volume', prefix: '€' },
  { key: 'netLoss', label: 'Net loss', prefix: '€' },
  { key: 'deposits', label: 'Deposits', prefix: '€' },
  { key: 'activeDays', label: 'Active days', suffix: 'd' },
];

let seq = 0;
const uid = (p: string) => { seq += 1; return `${p}-${Date.now()}-${seq}`; };

const TIER_TEMPLATE: { name: string; color: TierColor }[] = [
  { name: 'Bronze', color: 'bronze' },
  { name: 'Silver', color: 'silver' },
  { name: 'Gold', color: 'gold' },
  { name: 'Platinum', color: 'platinum' },
  { name: 'Diamond', color: 'diamond' },
  { name: 'VIP', color: 'diamond' },
];
const DEFAULT_CRIT: TierCriteria[] = [
  { wager: 0, netLoss: 0, deposits: 0, activeDays: 0 },
  { wager: 2500, netLoss: 250, deposits: 500, activeDays: 5 },
  { wager: 10000, netLoss: 1000, deposits: 2000, activeDays: 10 },
  { wager: 40000, netLoss: 4000, deposits: 8000, activeDays: 15 },
  { wager: 120000, netLoss: 12000, deposits: 25000, activeDays: 20 },
  { wager: 400000, netLoss: 40000, deposits: 80000, activeDays: 25 },
];
const DEFAULT_CASHBACK = [5, 8, 10, 12, 15, 20];
const DEFAULT_MULT = [1, 1.25, 1.5, 2, 2.5, 3];
const DEFAULT_PLAYERS = [5200, 2800, 1300, 500, 160, 40];

export function makeTier(index: number): DraftTier {
  const i = Math.min(index, TIER_TEMPLATE.length - 1);
  const tpl = TIER_TEMPLATE[i];
  const crit = DEFAULT_CRIT[i];
  const maint = { ...crit, wager: Math.round(crit.wager * 0.6), netLoss: Math.round(crit.netLoss * 0.6) };
  return {
    id: uid('tier'), name: tpl.name, color: tpl.color,
    entry: { ...crit }, maintain: maint,
    benefits: { cashbackPct: DEFAULT_CASHBACK[i], rewardMultiplier: DEFAULT_MULT[i], xpMultiplier: DEFAULT_MULT[i], withdrawalPerk: i >= 3 ? 'Priority (24h)' : 'Standard', vipManager: i >= 4, perks: i >= 2 ? ['Birthday bonus'] : [] },
    estPlayers: DEFAULT_PLAYERS[i],
  };
}

// ─────────────────────────────────────────────────────────────
// Rules (WHEN / IF / THEN)
// ─────────────────────────────────────────────────────────────
export interface RuleCondition { id: string; field: string; op: string; value: string; }
export interface ProgramRule { id: string; when: string; conditions: RuleCondition[]; thenAction: string; thenValue: string; }
export const RULE_WHEN = ['Player deposits', 'Wager settled', 'Period reset', 'Tier maintenance check', 'Net loss recorded'];
export const RULE_FIELDS = ['Wager volume (period)', 'Net loss (period)', 'Deposits (period)', 'Active days', 'Current tier'];
export const RULE_OPS = ['at least', 'at most', 'equals', 'below'];
export const RULE_ACTIONS = ['Promote one tier', 'Demote one tier', 'Hold current tier', 'Grant bonus credit', 'Add loyalty points'];

export function newCondition(): RuleCondition { return { id: uid('cond'), field: RULE_FIELDS[0], op: 'at least', value: '' }; }
export function newRule(): ProgramRule { return { id: uid('rule'), when: RULE_WHEN[1], conditions: [newCondition()], thenAction: RULE_ACTIONS[0], thenValue: '' }; }

const ACTIONS_NEED_VALUE = new Set(['Grant bonus credit', 'Add loyalty points']);
export function ruleErrors(r: ProgramRule): string[] {
  const e: string[] = [];
  if (!r.when) e.push('Select a trigger event');
  r.conditions.forEach((c, i) => { if (!c.value.trim()) e.push(`Condition ${i + 1} needs a value`); });
  if (ACTIONS_NEED_VALUE.has(r.thenAction) && !r.thenValue.trim()) e.push(`${r.thenAction} needs an amount`);
  return e;
}
export function ruleSummary(r: ProgramRule): string {
  const conds = r.conditions.filter((c) => c.value.trim()).map((c) => `${c.field} ${c.op} ${c.value}`).join(' and ');
  const then = r.thenAction + (r.thenValue.trim() ? ` (${r.thenValue})` : '');
  return `${r.when || 'When…'}${conds ? `, if ${conds}` : ''} → ${then}`;
}

// ─────────────────────────────────────────────────────────────
// Draft program
// ─────────────────────────────────────────────────────────────
export interface DraftProgram {
  id: string | null; // set when editing an existing program
  name: string;
  description: string;
  brandScope: 'brand_only' | 'network';
  brands: string[];
  scheduleMode: 'now' | 'scheduled';
  scheduledFor: string;
  resetCycle: ResetCycle;
  segment: string;
  jurisdictions: string[];
  owner: string;
  tiers: DraftTier[];
  cashback: CashbackConfigState;
  rules: ProgramRule[];
}

export function defaultDraft(): DraftProgram {
  return {
    id: null, name: '', description: '',
    brandScope: 'brand_only', brands: [],
    scheduleMode: 'now', scheduledFor: '',
    resetCycle: 'rolling_90d', segment: 'All active', jurisdictions: [], owner: 'Priya Nair',
    tiers: [0, 1, 2, 3, 4].map(makeTier),
    cashback: { model: 'net_loss', payoutFrequency: 'weekly', maxPayoutCap: 5000, minEligibility: 50, excludedSegments: [] },
    rules: [],
  };
}

// map an existing program into an editable draft
export function draftFromProgram(p: StatusProgram): DraftProgram {
  const d = defaultDraft();
  return {
    ...d, id: p.id, name: p.name, description: p.description,
    brandScope: p.brandScope, brands: [...p.brands],
    scheduleMode: p.status === 'scheduled' ? 'scheduled' : 'now', scheduledFor: p.scheduledFor ?? '',
    resetCycle: p.resetCycle, segment: p.segment, jurisdictions: [...p.jurisdictions], owner: p.owner,
    tiers: p.tiers.map((t, i) => {
      const base = makeTier(i);
      return { ...base, name: t.name, color: t.color, estPlayers: t.players || base.estPlayers, benefits: { ...base.benefits, cashbackPct: t.cashbackPct } };
    }),
  };
}

// ─────────────────────────────────────────────────────────────
// Tier threshold validation — flags inconsistent ladders
// ─────────────────────────────────────────────────────────────
export interface TierWarning { tierId: string; scope: 'entry' | 'maintain'; key: string; message: string; }
const CRIT_LABEL: Record<string, string> = { wager: 'wager volume', netLoss: 'net loss', deposits: 'deposits', activeDays: 'active days', cashbackPct: 'cashback' };

export function tierWarnings(tiers: DraftTier[]): TierWarning[] {
  const out: TierWarning[] = [];
  const cols = CRITERIA_COLS.map((c) => c.key);
  for (let i = 0; i < tiers.length; i++) {
    const t = tiers[i];
    const prev = i > 0 ? tiers[i - 1] : null;
    // maintenance thresholds must not exceed entry
    for (const k of cols) {
      if (t.entry[k] > 0 && t.maintain[k] > t.entry[k]) {
        out.push({ tierId: t.id, scope: 'maintain', key: k, message: `${t.name}: maintenance ${CRIT_LABEL[k]} is above its entry threshold` });
      }
    }
    if (!prev) continue;
    // entry thresholds should rise with rank
    for (const k of cols) {
      if (t.entry[k] < prev.entry[k]) {
        out.push({ tierId: t.id, scope: 'entry', key: k, message: `${t.name} entry ${CRIT_LABEL[k]} is below ${prev.name} — thresholds should increase with rank` });
      }
    }
    // cashback should not decrease as tiers climb
    if (t.benefits.cashbackPct < prev.benefits.cashbackPct) {
      out.push({ tierId: t.id, scope: 'entry', key: 'cashbackPct', message: `${t.name} cashback (${t.benefits.cashbackPct}%) is lower than ${prev.name} (${prev.benefits.cashbackPct}%)` });
    }
  }
  return out;
}

// ─────────────────────────────────────────────────────────────
// Liability math
// ─────────────────────────────────────────────────────────────
const MODEL_FACTOR: Record<CashbackModel, number> = { net_loss: 1, turnover: 1.45, ggr: 1.12 };
// avg monthly base metric per player, scaled by tier index
const TIER_BASE = [150, 340, 760, 1900, 4400, 9200];
export function tierBase(i: number) { return TIER_BASE[Math.min(i, TIER_BASE.length - 1)]; }

export function tierLiability(t: DraftTier, index: number, model: CashbackModel): number {
  return Math.round(t.estPlayers * tierBase(index) * MODEL_FACTOR[model] * (t.benefits.cashbackPct / 100));
}
export function monthlyLiability(d: DraftProgram): number {
  return d.tiers.reduce((s, t, i) => s + tierLiability(t, i, d.cashback.model), 0);
}
export function totalProjectedPlayers(d: DraftProgram): number {
  return d.tiers.reduce((s, t) => s + t.estPlayers, 0);
}

// ─────────────────────────────────────────────────────────────
// Tier movement preview — projected promotions/demotions at first reset
// ─────────────────────────────────────────────────────────────
export interface TierMovement { name: string; color: TierColor; promotedIn: number; demotedOut: number; net: number; }
const CYCLE_CHURN: Record<ResetCycle, number> = { monthly: 0.16, quarterly: 0.10, rolling_30d: 0.18, rolling_90d: 0.11, annual: 0.05, none: 0.02 };
export function tierMovement(d: DraftProgram): TierMovement[] {
  const churn = CYCLE_CHURN[d.resetCycle];
  return d.tiers.map((t, i, arr) => {
    const below = i > 0 ? arr[i - 1] : null;
    const promotedIn = below ? Math.round(below.estPlayers * churn * 0.55) : 0;
    const demotedOut = i > 0 ? Math.round(t.estPlayers * churn * 0.45) : 0; // bottom tier has nowhere lower
    return { name: t.name, color: t.color, promotedIn, demotedOut, net: promotedIn - demotedOut };
  });
}
export function movementTotals(d: DraftProgram): { promotions: number; demotions: number } {
  const m = tierMovement(d);
  return { promotions: m.reduce((s, x) => s + x.promotedIn, 0), demotions: m.reduce((s, x) => s + x.demotedOut, 0) };
}

// high-liability programs must route through approval before going live
export const APPROVAL_THRESHOLD = 250000;
export function needsApproval(d: DraftProgram): boolean { return monthlyLiability(d) >= APPROVAL_THRESHOLD; }

// ─────────────────────────────────────────────────────────────
// Validation
// ─────────────────────────────────────────────────────────────
export type StepState = 'complete' | 'partial' | 'empty';
export function stepStatus(d: DraftProgram): Record<ProgramStepId, StepState> {
  const setup: StepState = d.name && d.brands.length ? 'complete' : d.name || d.brands.length ? 'partial' : 'empty';
  const tiers: StepState = d.tiers.length >= 2 && d.tiers.every((t) => t.name.trim()) ? 'complete' : d.tiers.length ? 'partial' : 'empty';
  const benefits: StepState = d.tiers.some((t) => t.benefits.cashbackPct > 0) ? 'complete' : 'partial';
  const rules: StepState = d.rules.length ? 'complete' : 'empty';
  return { setup, tiers, benefits, rules, review: 'empty' };
}

// safety checks surfaced on the review step
export interface SafetyCheck { label: string; ok: boolean; note: string; }
export function safetyChecks(d: DraftProgram): SafetyCheck[] {
  const liab = monthlyLiability(d);
  const tw = tierWarnings(d.tiers);
  return [
    { label: 'Tier thresholds consistent', ok: tw.length === 0, note: tw.length === 0 ? 'Entry & maintenance thresholds rise cleanly with rank' : `${tw.length} inconsistent ${tw.length === 1 ? 'threshold' : 'thresholds'} — fix in Tiers` },
    { label: 'Jurisdiction mapping', ok: d.jurisdictions.length > 0, note: d.jurisdictions.length ? `${d.jurisdictions.join(', ')} mapped` : 'No jurisdictions selected' },
    { label: 'Max payout cap set', ok: d.cashback.maxPayoutCap > 0, note: d.cashback.maxPayoutCap > 0 ? `€${d.cashback.maxPayoutCap.toLocaleString()} per player` : 'No cap — unbounded liability' },
    { label: 'Minimum eligibility', ok: d.cashback.minEligibility > 0, note: d.cashback.minEligibility > 0 ? `From €${d.cashback.minEligibility} ${CASHBACK_MODEL_META[d.cashback.model].metric}` : 'All players eligible from €0' },
    { label: 'RG excluded players filtered', ok: true, note: 'Self-excluded players auto-removed at payout' },
    { label: 'Liability within budget', ok: liab < 250000, note: liab < 250000 ? 'Projected within monthly budget' : 'Projected liability exceeds €250k — approval required' },
  ];
}
